# Generated by Django 5.1.1 on 2024-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo3d',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
