# Generated by Django 5.1.1 on 2024-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_autenticacion', '0002_modelo3d_personalizacion_parte_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
